export const LOGIN = 'LOGIN'

export const MANGA = 'MANGA'
export const DETAILMANGA = 'DETAILMANGA'
export const ADDMANGA = 'ADDMANGA'
export const MANGAUSER = 'MANGAUSER'
export const UPDATEMANGA = 'UPDATEMANGA'
export const DELETEMANGA = 'DELETEMANGA'

export const ADDFAVORITE = 'ADDFAVORITE'
export const DETAILFAVORITE = 'DETAILFAVORITE'
export const DELETEFAVORITE = 'DELETEFAVORITE'
export const USERFAVORITE = 'USERFAVORITE'

export const CHAPTERMANGA = 'CHAPTERMANGA'
export const ADDCHAPTER = 'ADDCHAPTER'
export const DELETECHAPTER = 'DELETECHAPTER'
